### ISSUE TITLE
java.lang.NoClassDefFoundError: io/airlift/bootstrap/Bootstrap

### ISSUE THREAD

**Issue by rudolfdobias** [ebyhr/trino-storage#45]
Just tried to install it into my Trino 360 and this happens during startup:

```
2021-08-08T17:30:04.274Z	ERROR	main	io.trino.server.Server	io/airlift/bootstrap/Bootstrap
java.lang.NoClassDefFoundError: io/airlift/bootstrap/Bootstrap
	at org.ebyhr.trino.storage.StorageConnectorFactory.create(StorageConnectorFactory.java:50)
	at io.trino.connector.ConnectorManager.createConnector(ConnectorManager.java:360)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:215)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:207)
	at io.trino.connector.ConnectorManager.createCatalog(ConnectorManager.java:193)
	at io.trino.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
	at io.trino.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
	at io.trino.server.Server.doStart(Server.java:124)
	at io.trino.server.Server.lambda$start$0(Server.java:77)
	at io.trino.$gen.Trino_360____20210808_172957_1.run(Unknown Source)
	at io.trino.server.Server.start(Server.java:77)
	at io.trino.server.TrinoServer.main(TrinoServer.java:38)
Caused by: java.lang.ClassNotFoundException: io.airlift.bootstrap.Bootstrap
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at io.trino.server.PluginClassLoader.loadClass(PluginClassLoader.java:89)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more
```
	
Your plugin is initialized in catalog like this:
```yaml
  local.properties: |
    connector.name=storage
```
(I just _guess_ this might be the right connector.name because there is no mention in the docs.)

The mvn tests ran successfully and these jars are present at trino folder `/plugins/storage`:
```
trino-storage-360-services.jar
trino-storage-360-sources.jar  
trino-storage-360-test-sources.jar  
trino-storage-360-tests.jar	
trino-storage-360.jar
```

**Comment by ebyhr** [comment]
Please deploy jar files in trino-storage-360.zip.
